# Resolve static libraries from Zentra contrib/depends (cross-compile safe).
# Avoids fragile -lboost_* names and FindBoost failures on newer CMake.

function(zentra_depends_init)
  if(ZENTRA_DEPENDS_PREFIX)
    set(ZENTRA_DEPENDS_LIB_DIR "${ZENTRA_DEPENDS_PREFIX}/lib" PARENT_SCOPE)
    return()
  endif()
  if(CMAKE_FIND_ROOT_PATH)
    list(GET CMAKE_FIND_ROOT_PATH 0 _prefix)
    set(ZENTRA_DEPENDS_PREFIX "${_prefix}" PARENT_SCOPE)
    set(ZENTRA_DEPENDS_LIB_DIR "${_prefix}/lib" PARENT_SCOPE)
    return()
  endif()
  message(FATAL_ERROR "Set ZENTRA_DEPENDS_PREFIX to contrib/depends/<triplet>")
endfunction()

# Pick one static archive (prefers release, non-debug tagged Boost).
function(zentra_pick_static_archive outvar candidates)
  set(_pick "")
  foreach(_cand IN LISTS candidates)
    if(_cand MATCHES "-d-" OR _cand MATCHES "-gd-")
      continue()
    endif()
    set(_pick "${_cand}")
    break()
  endforeach()
  if(NOT _pick AND candidates)
    list(GET candidates 0 _pick)
  endif()
  set(${outvar} "${_pick}" PARENT_SCOPE)
endfunction()

function(zentra_find_static_lib outvar libdir basename)
  file(GLOB _cand
    "${libdir}/lib${basename}.a"
    "${libdir}/${basename}.a"
    "${libdir}/lib${basename}-*.a"
    "${libdir}/${basename}-*.a")
  if(NOT _cand)
    set(${outvar} "" PARENT_SCOPE)
    return()
  endif()
  zentra_pick_static_archive(_pick "${_cand}")
  set(${outvar} "${_pick}" PARENT_SCOPE)
endfunction()

function(zentra_find_static_lib_required outvar libdir basename)
  zentra_find_static_lib(_lib "${libdir}" "${basename}")
  if(NOT _lib)
    message(FATAL_ERROR "Missing depends library ${basename} under ${libdir}")
  endif()
  set(${outvar} "${_lib}" PARENT_SCOPE)
endfunction()

function(zentra_find_boost_libs outvar libdir)
  set(_boost "")
  foreach(_comp IN ITEMS
      system chrono filesystem thread serialization locale regex program_options date_time)
    file(GLOB _cand "${libdir}/libboost_${_comp}*.a")
    if(NOT _cand)
      if(_comp STREQUAL "locale" AND ANDROID)
        message(STATUS "Boost locale not found (skipped on Android): ${libdir}")
        continue()
      endif()
      message(FATAL_ERROR "Boost component ${_comp} not found under ${libdir}")
    endif()
    zentra_pick_static_archive(_pick "${_cand}")
    list(APPEND _boost "${_pick}")
  endforeach()
  set(${outvar} "${_boost}" PARENT_SCOPE)
endfunction()

function(zentra_find_openssl_libs sslvar cryptovar libdir)
  zentra_find_static_lib_required(_ssl "${libdir}" "ssl")
  zentra_find_static_lib_required(_crypto "${libdir}" "crypto")
  set(${sslvar} "${_ssl}" PARENT_SCOPE)
  set(${cryptovar} "${_crypto}" PARENT_SCOPE)
endfunction()

# Libraries required when linking wallet_api static archives for each platform class.
function(zentra_depends_external_libs outvar)
  zentra_depends_init()
  set(_libdir "${ZENTRA_DEPENDS_LIB_DIR}")
  set(_libs "")

  zentra_find_boost_libs(_boost "${_libdir}")
  list(APPEND _libs ${_boost})

  zentra_find_openssl_libs(_ssl _crypto "${_libdir}")
  list(APPEND _libs "${_ssl}" "${_crypto}")

  foreach(_name IN ITEMS z sodium iconv expat)
    zentra_find_static_lib(_lib "${_libdir}" "${_name}")
    if(_lib)
      list(APPEND _libs "${_lib}")
    endif()
  endforeach()

  if(ANDROID)
    foreach(_name IN ITEMS atomic zmq unbound ncurses readline tinfo)
      zentra_find_static_lib(_lib "${_libdir}" "${_name}")
      if(_lib)
        list(APPEND _libs "${_lib}")
      endif()
    endforeach()
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    zentra_find_static_lib(_protobuf "${_libdir}" "protobuf")
    if(_protobuf)
      list(APPEND _libs "${_protobuf}")
    endif()
    file(GLOB _icu "${_libdir}/libicu*.a")
    if(_icu)
      list(APPEND _libs ${_icu})
    endif()
    foreach(_name IN ITEMS zmq unbound hidapi hidapi-libusb usb-1.0 pgm norm)
      zentra_find_static_lib(_lib "${_libdir}" "${_name}")
      if(_lib)
        list(APPEND _libs "${_lib}")
      endif()
    endforeach()
  else()
    foreach(_name IN ITEMS protobuf zmq unbound hidapi usb-1.0 pgm norm)
      zentra_find_static_lib(_lib "${_libdir}" "${_name}")
      if(_lib)
        list(APPEND _libs "${_lib}")
      endif()
    endforeach()
  endif()

  set(${outvar} "${_libs}" PARENT_SCOPE)
endfunction()
